# Testing Model

In [3]:
# USAGE
# python basic_cnn.py

# import the necessary packages
import tensorflow as tf
from PIL import Image
from imutils import paths
import numpy as np
from tensorflow.keras.utils import img_to_array
import os
import os.path  
import pickle
import imutils
import cv2
from tkinter import *
from PIL import Image
from PIL import ImageTk
import tkinter.filedialog as file
import cv2
model_name = 'D:\coding\AI_code\keras\melon\weed_model_dim_32x32.sav'
IMAGE_DIMS = (32, 32, 3)
def select_image():
	# grab a reference to the image panels
	global panelA, panelB

	# open a file chooser dialog and allow the user to select an input
	# image
	path = file.askopenfilename()

	# ensure a file path was selected
	if len(path) > 0:
		image = cv2.imread(path)
		orig = cv2.imread(path)
		edged= cv2.imread(path)
		orig = cv2.cvtColor(orig, cv2.COLOR_BGR2RGB)
		edged= cv2.cvtColor(edged, cv2.COLOR_BGR2RGB)
		image = cv2.resize(image, (IMAGE_DIMS[1], IMAGE_DIMS[0]))
		image = image.astype("float") / 255.0
		image = img_to_array(image)
		image = np.expand_dims(image, axis=0)
		filename = model_name
#		loaded_model = pickle.load(open(filename, 'rb'))
		loaded_model = tf.keras.models.load_model(filename)
		print(loaded_model)
		predictions = loaded_model.predict(image)[0]
		max_predict = max(predictions)
		print(predictions)
		print(max_predict)
		label =''
		prob = max_predict
		if max_predict == predictions[0] :
			label = 'Daun Sakit'
		if max_predict == predictions[1] :
			label = 'Daun Sehat'
		if max_predict == predictions[2] :
			label = 'Tanah'

		label = "{}: {:.2f} %".format(label, prob * 100)
		print(label)
		scale_percent = 40 # percent of original size
		width = int(300)
		height = int(400)
		dim = (width, height)
		orig = cv2.resize(orig,dim, interpolation = cv2.INTER_AREA)
		width = int(300)
		height = int(400)
		dim = (width, height)
		edged= cv2.resize(edged,dim, interpolation = cv2.INTER_AREA)
		edged = cv2.putText(edged, label, (10, 25),  cv2.FONT_HERSHEY_SIMPLEX,
			0.7, (0, 255, 0), 2)	
		edged = Image.fromarray(edged)
		orig= Image.fromarray(orig)
		orig = ImageTk.PhotoImage(orig)
		
		edged = ImageTk.PhotoImage(edged)

		# if the panels are None, initialize them
		if panelA is None or panelB is None:
			# the first panel will store our original image
			panelA = Label(image=orig)
			panelA.image = orig
			panelA.pack(side="left", padx=10, pady=10)

			# while the second panel will store the edge map
			panelB = Label(image=edged)
			panelB.image = edged
			panelB.pack(side="right", padx=10, pady=10)

		# otherwise, update the image panels
		else:
			# update the pannels
			panelA.configure(image=orig)
			panelB.configure(image=edged)
			panelA.image= orig
			panelB.image = edged

# initialize the window toolkit along with the two image panels

root = Tk()
panelA = None
panelB = None

# create a button, then when pressed, will trigger a file chooser
# dialog and allow the user to select an input image; then add the
# button the GUI
btn = Button(root, text="Select an image", command=select_image)
btn.pack(side="bottom", fill="both", expand="yes", padx="10", pady="10")

# kick off the GUI
root.mainloop()

1/1 [==============================] - 0s 66ms/step
[9.9696940e-01 3.0306259e-03 3.9680431e-10]
0.9969694
Daun Sakit: 99.70 %
1/1 [==============================] - 0s 57ms/step
[3.8891907e-13 1.0000000e+00 8.1375379e-10]
1.0
Daun Sehat: 100.00 %
1/1 [==============================] - 0s 59ms/step
[1.1907780e-14 1.9461595e-10 1.0000000e+00]
1.0
Tanah: 100.00 %
